export enum PropertyTypeEnum {
  MAISON = 'MAISON',
  APPARTEMENT = 'APPARTEMENT',
  LOCATION = 'LOCATION',
  TERRAIN = 'TERRAIN',
  CHAMBRE = 'CHAMBRE',
  BUREAU = 'BUREAU',
  IMMEUBLE = ' IMMEUBLE',
  LOCAL_COMMERCIALE = ' LOCAL_COMMERCIALE',
  FONTS_DE_COMMERCE = 'FONTS_DE_COMMERCE',
}
